spring.datasource.url=jdbc:mysql://localhost:3306/ai
spring.datasource.username=root
spring.datasource.password=@Ganu0031
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
gemini.api.key=AIzaSyCZdsJrq_-ITme4iv7sTSkfm-tvkotrUOs
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent